import { Inter, Roboto } from "next/font/google";
import NavBar from "@/components/NavBar";
import "./globals.css";
import Head from "next/head";

//============FONT GOOGLE===============
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "greek", "cyrillic"],
  style: ["italic", "normal"],
  display: "auto",
});
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Black Monkey",
  description: "Generated by Ariel Zaarte witch NextJs",
  //===========Other metadates======================
  generator: "Next.js",
  applicationName: "Tienda Responsive",
  referrer: "origin-when-cross-origin",
  keywords: ["Next.js", "React", "JavaScript"],
  authors: [{ name: "Ariel zarate", url: "https://github.com/arielZarate" }],
  creator: "Ariel Zarate",
  // publisher: "Sebastian Markbåge",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Agregar favicon */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* importacion de la clase roboto de google fonts */}
      <body className={roboto.className}>
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
