"use client";

import Home from "./page";

import "./globals.css";

//=======FUENTES=================================
import { Inter, Roboto } from "next/font/google";
import { useState } from "react";
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "greek", "cyrillic"],
  style: ["italic", "normal"],
  display: "auto",
});
const inter = Inter({ subsets: ["latin"] });
//===============================================
/* export const metadata = {
  title: "CreaTE APP Notices by Ariel Zarate",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Create REQREST API by Ariel Zarate</title>
        <meta name="description" content="Generated by create next app" />
      </head>

      <body className={roboto.className}>
        <main>
          {/*   {selectedUserId ? <Home selectedUserId={selectedUserId} /> : children} */}

          {children}
          {/* <Home selectedUserId={selectedUserId} /> */}
        </main>
      </body>
    </html>
  );
}
